check50:
  checks:
    check_path:
      - run: python3 degrees.py small
        stdin: 
          - Emma Watson
          - Kevin Bacon
        stdout: Not connected.
  files:
    - !exclude "*"
    - !require "util.py"
    - !require "degrees.py"
  dependencies:
    - "numpy>=1.18.4"
    - "pandas>=1.0.3"
    - "networkx>=2.4"