check50:
  checks: __init__.py
  files:
    - !exclude "*"
    - !require "util.py"
    - !require "degrees.py"
  dependencies:
    - "numpy>=1.18.4"
    - "pandas>=1.0.3"
    - "networkx>=2.4"